function dimensions = tableFormula()
    width = 28;
    height = 25;
    base = 3.5;
    theta = linspace(rad2deg(-pi), rad2deg(pi));
    f = @(theta) height * cosd(theta) + base - width * sind(theta);
    plot(theta, f(theta), "LineWidth", 3);
    xlabel("X-Axis");
    ylabel("Y-Axis");
    grid on;
    title("Part A");
    equation = '25 * cos(theta) + 3.5 - 28 * sin(theta)';
    [bisectionRoot, bisectionIterations] = bisect2(equation, [0, pi/2], deg2rad(1));
    bisectionRoot = rad2deg(bisectionRoot);
    fprintf('The root obtianed by Bisection method: %f\nIt took %d iterations \n\n', bisectionRoot, bisectionIterations);
    fixedPointFunc = 'asin((25 * cos(theta) + 3.5) / 28)';
    [fixedPointRoot, fixedPointIterations] = fixedpt(fixedPointFunc, 0, deg2rad(1));
    fixedPointRoot = rad2deg(fixedPointRoot);
    fprintf('The root obtianed by Fixed Point method: %f\nIt took %d iterations \n\n', fixedPointRoot, fixedPointIterations);
    newtonDerivative = '-25 * sin(theta) - 28 * cos(theta)';
    [newtonRoot, newtonIterations] = newton(equation, newtonDerivative, 0, deg2rad(1));
    newtonRoot = rad2deg(newtonRoot);
    fprintf('The root obtianed by newton method: %f\nIt took %d iterations \n\n', newtonRoot, newtonIterations);
    theta1 = acos((-base * height + sqrt((base^2 * height^2) + (height^2 + width^2) * (width^2 - base^2))) / (height^2 + width^2));
    theta1 = rad2deg(theta1);
    fprintf('Exact Root: %f\n\n', theta1);
    errorb = abs(theta1 - bisectionRoot);
    errorf = (fixedPointRoot - theta1) ;
    errorn = abs(theta1 - newtonRoot);
    errorb1 = abs(bisectionRoot - theta1)/theta1 ;
    errorf1 = (fixedPointRoot - theta1)/theta1 ;
    errorn1 = abs(theta1 - newtonRoot)/theta1;
    fprintf('Absolute error for bisecton: %f\n', errorb);
    fprintf('Relative error for bisecton: %f\n\n', errorb1);
    fprintf('Absolute error for Fixed Point: %f\n', errorf);
    fprintf('Relative error for Fixed Point: %f\n\n', errorf1);
    fprintf('Absolute error for Newton: %f\n', errorn);
    fprintf('Relative error for Newton: %f\n\n', errorn1);
    d2Approx = (height / (2 * sind(newtonRoot)));
    c = base / tand(newtonRoot);
    a = base / tand(rad2deg(pi/2) - newtonRoot);
    d1Approx = d2Approx - a - c;
    fprintf('Approximate Dimensions: \nd1: %f\nd2: %f\n\n', d1Approx, d2Approx);
    d2Exact = (height / (2 * sind(theta1)));
    c = base / tand(theta1);
    a = base / tand(rad2deg(pi/2) - theta1);
    d1Exact = d2Exact - a - c;
    fprintf('Exact Dimensions: \nd1exact: %f\nd2exact: %f\n', d1Exact, d2Exact);
    r1 = abs(d1Exact - d1Approx) ;
    r2 = abs(d2Exact - d2Approx);
    fprintf('Absolute error for d1: %f\nAbsolute error for d2: %f\n', r1, r2);
end

